name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: misodengaku/tex:master

    steps:
    - uses: actions/checkout@v3
    
    - name: Build pdf
      run: make latexpdfja
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/latex/CHANGEME.pdf
