name: Generate PDF

env:
  FILENAME: CHANGEME.pdf

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: misodengaku/tex:7.2.6

    steps:
      - uses: actions/checkout@v4

      - name: Build pdf
        run: make latexpdfja

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "build/latex/$FILENAME"
